version: "3.9"

x-env: &api_env
  # App config
  DEBUG: ${DEBUG:-false}

  # GelDB client (non-secret bits)
  GEL_HOST: ${GEL_HOST:?set in .env}
  GEL_PORT: ${GEL_PORT:?set in .env}
  GEL_CLIENT_TLS_SECURITY: ${GEL_CLIENT_TLS_SECURITY:?set in .env}

  # OIDC config — non-secrets
  KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL:?set in .env}
  KEYCLOAK_REALM: ${KEYCLOAK_REALM:?set in .env}
  KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:?set in .env}
  KEYCLOAK_ALLOWED_REDIRECTS: ${KEYCLOAK_ALLOWED_REDIRECTS:?set in .env}
  AUTH_BASE_DOMAIN: ${AUTH_BASE_DOMAIN:?set in .env}

services:
  api:
    build: .
    command: gunicorn -c gunicorn.conf.py main:app
    env_file: .env
    environment:
      <<: *api_env
      GEL_USER: ${GEL_USER:?define in GitHub Secrets or export in shell}
      GEL_PASSWORD: ${GEL_PASSWORD:?define in GitHub Secrets or export in shell}
    depends_on:
      gel:
        condition: service_healthy
    ports:
      - "5000:5000"
    restart: always
